<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
		<title><?= $title; ?></title>
		
		<!-- Add to homescreen for Chrome on Android -->
		<!--meta name="mobile-web-app-capable" content="yes">
		<link rel="icon" sizes="196x196" href="images/touch/chrome-touch-icon-196x196.png"-->
		
		<!-- Add to homescreen for Safari on iOS -->
		<!--meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta name="apple-mobile-web-app-title" content=""-->
		
		<!-- Tile icon for Win8 (144x144 + tile color) -->
		<!--meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
		<meta name="msapplication-TileColor" content="#3372DF"-->
		
		<?php foreach ($styles as $style) : ?>
			<link rel="stylesheet" href="<?= $style; ?>">
		<?php endforeach; ?>
		
		<?php foreach ($headScripts as $script) : ?>
			<script src="<?= $script; ?>"></script>
		<?php endforeach; ?>
		
	</head>
	<body>
		
		<?= $content; ?>
		
		<?php foreach ($footScripts as $script) : ?>
			<script src="<?= $script; ?>"></script>
		<?php endforeach; ?>
		
	</body>
</html>
